# options for analysis running
run:
  linters-settings:
    errcheck:
      # report about not checking of errors in type assetions: `a := b.(MyStruct)`;
      check-type-assertions: true
      # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
      check-blank: false
    govet:
      # report about shadowed variables
      check-shadowing: true
    gocyclo:
      # minimal code complexity to report, 30 by default (but we recommend 10-20)
      min-complexity: 30
    lll:
      # max line length, lines longer will be reported. Default is 120.
      # '\t' is counted as 1 character by default, and can be changed with the tab-width option
      line-length: 300
    unused:
      # treat code as a program (not a library) and report unused exported identifiers
      check-exported: true
    unparam:
      # Inspect exported functions, default is false. Set to true if no external program/library imports your code.
      check-exported: true
    nakedret:
      # make an issue if func has more lines of code than this setting and it has naked returns
      max-func-lines: 60
    prealloc:
      # Report preallocation suggestions only on simple loops that have no returns/breaks/continues/gotos in them.
      simple: true
      range-loops: true # Report preallocation suggestions on range loops
      for-loops: false # Report preallocation suggestions on for loops
  
  linters:
    disable-all: true
    enable:
      - govet
      - errcheck
      - gocyclo
      - structcheck
      - varcheck
      - ineffassign
      - deadcode
      - typecheck
      - golint
      - interfacer
      - unconvert
      - goconst
      - gocyclo
      - staticcheck
      - unused
      - gosimple
      - gofmt
      - dupl
      - gosec
      - lll
      - megacheck
      - gocritic
    fast: false
  
  issues:
    # Independently from option `exclude` we use default exclude patterns,
    # it can be disabled by this option. To list all
    # excluded by default patterns execute `golangci-lint run --help`.
    # Default value for this option is true.
    exclude-use-default: true
    exclude:
      - "File is not `goimports`-ed"
      - "is unused"