// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "ovr.shevtsov@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/{channel}": {
            "get": {
                "description": "get messages for channel",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "get messages for channel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "channel",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "pagination offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "pagination limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.HooksByChannel"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "post message",
                "consumes": [
                    "application/json"
                ],
                "summary": "post message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "channel",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "message",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    {
                        "type": "integer",
                        "description": "fail requests until timestamp",
                        "name": "failUntil",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "do not handle message by service and just reply with status code",
                        "name": "justreply",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "description": "delete channel",
                "consumes": [
                    "application/json"
                ],
                "summary": "delete channel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "channel",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "entities.Hook": {
            "type": "object",
            "properties": {
                "channel": {
                    "type": "string"
                },
                "created_at": {
                    "type": "integer"
                },
                "headers": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "payload": {
                    "type": "string"
                },
                "statusOk": {
                    "type": "boolean"
                }
            }
        },
        "entities.HooksByChannel": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Hook"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "webhook-api.shelex.dev",
	BasePath:         "/",
	Schemes:          []string{"https"},
	Title:            "webhook listener API",
	Description:      "webhook listener api",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
